const kCountries = [
    {turnOrder: 0,  code: "??", flatName: "neutral"},
    {turnOrder: 1,  code: "os", flatName: "orangestar"},
    {turnOrder: 2,  code: "bm", flatName: "bluemoon"},
    {turnOrder: 3,  code: "ge", flatName: "greenearth"},
    {turnOrder: 4,  code: "yc", flatName: "yellowcomet"},
    {turnOrder: 5,  code: "bh", flatName: "blackhole"},
    {turnOrder: 6,  code: "rf", flatName: "redfire"},
    {turnOrder: 7,  code: "gs", flatName: "greysky"},
    {turnOrder: 8,  code: "bd", flatName: "browndesert"},
    {turnOrder: 9,  code: "ab", flatName: "amberblaze"},
    {turnOrder: 10, code: "js", flatName: "jadesun"},
    {turnOrder: 11, code: "ci", flatName: "cobaltice"},
    {turnOrder: 12, code: "pc", flatName: "pinkcosmos"},
    {turnOrder: 13, code: "tg", flatName: "tealgalaxy"},
    {turnOrder: 14, code: "pl", flatName: "purplelightning"},
    {turnOrder: 15, code: "ar", flatName: "acidrain"},
    {turnOrder: 16, code: "wn", flatName: "whitenova"},
];
